config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resource :adwords_settings do
      collection do
        post :dismiss_alert
      end
    end
  end
end

app/models/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :conversion_id,       :integer, default: 0
  preference :conversion_language, :string,  default: 'en_GB'
  preference :conversion_color,    :string,  default: '666666'
  preference :conversion_label,    :string,  default: 'Purchase'
  preference :conversion_format,   :string,  default: "3"
end

app/controllers/spree/admin/adwords_settings_controller.rb
module Spree
  module Admin
    class AdwordsSettingsController < Spree::Admin::BaseController
      def show
        @preferences = ['conversion_id', 'conversion_language', 'conversion_color',
                        'conversion_label', 'conversion_format']
      end

      def edit
        @preferences = [:conversion_id, :conversion_language, :conversion_color,
                        :conversion_label, :conversion_format]
      end

      def update
        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end

        redirect_to admin_adwords_settings_path
      end

      def dismiss_alert
        if request.xhr? and params[:alert_id]
          dismissed = Spree::Config[:dismissed_spree_alerts] || ''
          Spree::Config.set :dismissed_spree_alerts => dismissed.split(',').push(params[:alert_id]).join(',')
          filter_dismissed_alerts
          render :nothing => true
        end
      end
    end
  end
end

app/views/spree/admin/adwords_settings/_adword_config.erb
<tr>
  <td><%= link_to t(:adwords_conversion), admin_adwords_settings_path %></td>
  <td>Config settings for adwords conversion</td>
</tr>

app/views/spree/admin/adwords_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:edit_adwords_settings) %>
<% end %>

<%= form_tag admin_adwords_settings_path, :method => :put do %>
  <fieldset id="preferences" data-hook>
    <legend>Google Parameters</legend>
    <% @preferences.each do |key|
        type = Spree::Config.preference_type(key) %>
      <div class="field">
        <%= label_tag(key, t(key) + ': ') + tag(:br) if type != :boolean %>
        <%= preference_field_tag(key, Spree::Config[key], :type => type) %>
        <%= label_tag(key, t(key)) + tag(:br) if type == :boolean %>
      </div>
    <% end %>
  </fieldset>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_adwords_settings_url %>
  </p>
<% end %>

<script>
  $('#currency').select2();
</script>

app/views/spree/admin/adwords_settings/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:adwords_settings) %>
<% end %>

<table data-hook="preferences">
  <% @preferences.each do |key| %>
    <tr>
      <td scope="row"><%= t(key) %>:</td>
      <td><%= Spree::Config[key] %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to_with_icon 'edit', t(:edit), edit_admin_adwords_settings_path, :id => 'admin_adwords_settings_link' %></p>

app/views/spree/orders/_google_conversion.erb
<script type="text/javascript">
  /* <![CDATA[ */
  var google_conversion_id = <%= Spree::Config[:conversion_id] %>;
  var google_conversion_language = "<%= Spree::Config[:conversion_language] %>";
  var google_conversion_format = "<%= Spree::Config[:conversion_format] %>";
  var google_conversion_color = "<%= Spree::Config[:conversion_color] %>";
  var google_conversion_label = "<%= Spree::Config[:conversion_label] %>";
  var google_conversion_value = <%= @order.total %>;
  var google_remarketing_only = false;
  /* ]]> */ 
</script>
<script type="text/javascript"
  src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
  <img height=1 width=1 border=0
  src="http://www.googleadservices.com/pagead/
  conversion/<%= Spree::Config[:conversion_id] %>/?value=
  <%= @order.total %>&label=<%= Spree::Config[:conversion_language] %>&guid=ON&script=0">
</noscript>